networks:
  proxy-tier:
    external: false

services:
  # Nginx Proxy Manager (The Front Door)
  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./data/proxy:/data
      - ./data/letsencrypt:/etc/letsencrypt
    networks:
      - proxy-tier

  # Landing Page (Your CV)
  landing:
    image: nginx:alpine
    container_name: alpine
    restart: unless-stopped
    volumes:
      - ./landing-page:/usr/share/nginx/html:ro
    networks:
      - proxy-tier

  # Git (Forgejo)
  git:
    image: codeberg.org/forgejo/forgejo:15
    container_name: git
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./data/git:/data
    ports:
      - "222:22"
    networks:
      - proxy-tier

  # Database for Nextcloud
  cloud-db:
    image: mariadb:latest
    container_name: cloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - ./.env
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - ./data/c-db:/var/lib/mysql
    networks:
      - proxy-tier

  # Cloud Storage (Nextcloud)
  cloud:
    image: nextcloud:latest
    container_name: cloud
    restart: unless-stopped
    depends_on:
      - cloud-db
    env_file:
      - .env
    volumes:
      - ./data/cloud:/var/www/html/data
    networks:
      - proxy-tier