services:
  # Nginx Proxy Manager (The Front Door)
  proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./data/proxy:/data
      - ./data/letsencrypt:/etc/letsencrypt

  # Landing Page (Your CV)
  landing:
    image: nginx:alpine
    restart: always
    volumes:
      - ./landing-page:/usr/share/nginx/html:ro
    # No ports needed here! Proxy handles it.

  # Git (Forgejo)
  git:
    image: codeberg.org/forgejo/forgejo:15
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000 # Fixed the colon to an underscore
    volumes:
      - ./data/git:/data
    ports:
      - "222:22" # Keep this so you can SSH clone code

  # Database for Nextcloud
  cloud-db:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - ./.env
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - ./data/c-db:/var/lib/mysql

  # Cloud Storage (Nextcloud)
  cloud:
    image: nextcloud:latest
    restart: always
    depends_on:
      - cloud-db
    env_file:
      - .env
    volumes:
      - ./data/cloud:/var/www/html/data
      
  # TeamSpeak
  teamspeak:
    image: teamspeak:latest
    restart: always
    environment:
      - TS3SERVER_LICENSE=accept
    volumes:
      - ./data/teamspeak:/var/ts3server
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"